### ISSUE TITLE
Overflowing scale with a quite reasonable number.

### ISSUE THREAD

**Issue by pimeys** [paupino/rust-decimal#251] opened 2020-07-03 12:26 UTC
If you call `Decimal::new(10000, 0)`, this will panic out with an error:

```
thread 'test_prepared_type_decimal' panicked at 'Scale exceeds the maximum precision allowed: 4294967292 > 28',
/home/pimeys/.cargo/registry/src/github.com-1ecc6299db9ec823/rust_decimal-1.6.0/src/decimal.rs:191:13
```

This feels like a bug, the number is 10000 and should not overflow anything.

**Comment by paupino** [comment] 2020-07-03 16:33
Hi @pimeys - I can't replicate this using `1.6.0` in both debug/release for stable/beta. The panic you're getting indicates this code is getting triggered:
```
        if scale > MAX_PRECISION {
            panic!(
                "Scale exceeds the maximum precision allowed: {} > {}",
                scale, MAX_PRECISION
            );
        }
```

Reproduced the successful case in this branch: https://github.com/paupino/rust-decimal/blob/issue/251/tests/decimal_tests.rs#L1613-L1621

Can you perhaps share the breaking code and some further details?

**Comment by pimeys** [comment] 2020-07-03 16:47
Here: https://github.com/pimeys/sqlx/blob/decimal/tests/postgres/types.rs#L347

So, when this is enabled either with `from_str` or `new(10000, 0)`, the test panics with the given error...

**Comment by pimeys** [comment] 2020-07-03 16:51
To reproduce:

- Clone the branch
- In the `tests` directory, start the database `docker-compose run -d --p 5432:5432 postgres_13`
- Run the test

```bash
DATABASE_URL="postgres://postgres:password@localhost:5432/sqlx" cargo test --no-default-features --features postgres,all-types,runtime-async-std
```

**Comment by paupino** [comment] 2020-07-03 18:27
Looking into this - it doesn't appear to be from the Rust Decimal library - it's arising from the scale being calculated here: https://github.com/pimeys/sqlx/blob/decimal/sqlx-core/src/postgres/types/decimal.rs#L60

The failed case, is being given digit length 1 and a weight of 1 - which makes sense given PostgreSQL grouping in 10,000's. The formula here however falls down and is calculating a negative number. i.e.
```
(digits.len() - weight - 1) * 4
= (1 - 1 - 1) * 4
= -4
```

Of course, converting this to a `u32` for a scale is overflowing - thus giving the `4294967292` number.

Rust Decimal does a similar calculation to convert a PG type to a Decimal number library type here: https://github.com/paupino/rust-decimal/blob/master/src/postgres.rs#L44
It may be worthwhile either using that for inspiration or leveraging that same code if possible?

**Comment by paupino** [comment] 2020-07-03 18:28
Closing this since it's not an error inside Rust Decimal. Please feel free to reopen if you find something different.

**Closed by paupino** 2020-07-03 18:28 UTC

**Comment by pimeys** [comment] 2020-07-03 18:37
Thank you and sorry for bothering!
